name: "🚀 Publish package to GITHUB"

on:
    push:
        branches: 
          - main

jobs:
    release:
        name: 🚀 release github
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
              
            - name: 🟢 node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 18.x
                  registry-url: https://registry.npmjs.org
                  
            - name: 🚀 publish package to github
              run: npm publish
              working-directory: ./
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GIT_PACKAGES_DOWNLOAD_AUTH_TOKEN}}
